version: 2.1

orbs:
  python: circleci/python@1.2.1
  cypress: cypress-io/cypress@3.0.0

jobs:
  build:
    docker:
      - image: cimg/python:3.10
      - image: postgres:14.1
        environment:
          POSTGRES_USER: $POSTGRES_USER
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          POSTGRES_DB: $POSTGRES_DB  
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libxmlsec1-dev libxml2-dev libxslt1-dev xmlsec1
          environment:
            LC_ALL: C.UTF-8
            LANG: C.UTF-8
      - run:
          name: Install Python dependencies
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pip install --upgrade pip
            pip install Django
          environment:
            LC_ALL: C.UTF-8
            LANG: C.UTF-8   
      - run:
          name: Migrate database
          command: |
            source venv/bin/activate
            export DATABASE_URL=postgresql://'$POSTGRES_USER':'$POSTGRES_PASSWORD'@localhost/'$POSTGRES_DB'
            python manage.py migrate --noinput
            
      - run:
          name: Collect Static Files
          command: |
            source venv/bin/activate
            python manage.py collectstatic --noinput
      - run:
          name: Start and test application
          command: |
            source venv/bin/activate
            python manage.py runserver 127.0.0.1:8000 &
            
      

workflows:
  build:
    jobs:
      - build